### ISSUE TITLE
CV-partner ingestor timer ut

### ISSUE THREAD

**Issue by henrikav** [knowit/Dataplattform#447]
# Oppgavebeskrivelse
Ved release 1.0.4 så dukket det opp en "Connection timed out"-error. Dette var fordi det var en hook som trigger cvpartner ingestoren ved deploy. Denne ingestoren brukte veldig lang tid og forårsaket en timeout. 
 
Her må det gjøres om slik at man kan trigge ingestion etter deploy på en måte som ikke stopper hele workflowen.
Følgende kode ble fjernet for å stoppe timeout:
```
hooks:
  - name: 'Invoke ingestor'
    trigger: postDeploy
    type: invoke
    value: ingest
```
